### ISSUE TITLE
Interpolating near endpoints?

### ISSUE THREAD

**Issue by bennlich** [osuushi/Smooth.js#4]
The example in the readme works:

````
var s = Smooth([1, 2, 3, 4]);
console.log(s(1));          // => 2
console.log(s(1.5));        // => 2.5
````

but if you try to interpolate between the first and second indices, you get the following:

````
console.log(s(0.5));       // => 1.4375
````

Is this expected?

**Comment by osuushi** [comment]
This is expected. The default interpolation method is cubic, so the curve produced won't be a straight line.

In this particular case, the clipping mode also comes into play because cubic interpolation uses 4 control points at all times. So if you ask what `s(1.5)` is, we look at the elements 0, 1, 2, and 3 in the array (two to the left and two to the right of our parameter, 1.5).

But if you ask for `s(0.5)`, we have to look at indexes -1, 0, 1, and 2. This poses a problem, because there *is* no index -1 in the source array. When we need out of bounds values, we use the "clipping mode" to decide what to do. The clipping mode basically lets us pretend that the input array extends forever in both directions.

The default clipping mode is "clamp", which basically means "repeat the first and last elements forever". So if you asked for `s(-20)`, you'd get `1`. If you ask for `s(50000)`, you'll get `3`. As a result, your curve will flatten out around the boundaries.

There are some other clipping modes that have other effects, but in this particular case, none of them will cause `s(0.5)` to output `1.5`.

However, you will if you use the `linear`  interpolation method, since it only relies on two points. You'll also lose some smoothness though.
